// <auto-generated />
namespace WingtipToys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddAspNetUsersField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAspNetUsersField));
        
        string IMigrationMetadata.Id
        {
            get { return "201710182220483_AddAspNetUsersField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
