<%@ Page Title="User Profile" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Profile.aspx.cs" Inherits="WingtipToys.Account.Profile" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">

    <h2><%: Title %></h2>
    <p class="text-danger">
        <asp:Literal runat="server" ID="ErrorMessage" />
    </p>
<p><h7><b>Click on [Edit] to update your profile information:</b></h7><br>
 <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
    <asp:GridView runat="server" ID="userProfileGrid"  CssClass="grid"
    ItemType="WingtipToys.Models.ApplicationUser" DataKeyNames="Id" 
    SelectMethod="userProfileGrid_GetDataByID" UpdateMethod="userProfileGrid_UpdateItem"
    AutoGenerateEditButton="true" AutoGenerateDeleteButton="false"  
    AutoGenerateColumns="false">
    <Columns>
        <%--<asp:DynamicField DataField="FirstName" />
        <asp:DynamicField DataField="LastName" />--%>
        <asp:BoundField HeaderText="University ID" DataField="UniversityID" />
        <asp:BoundField HeaderText="First Name" DataField="FirstName" />
        <asp:BoundField HeaderText="Last Name" DataField="LastName" />
    </Columns>
    </asp:GridView>
</asp:Content>